#!/usr/bin/python3
import os
from statistics import mean

#Define the Clear Function
def clear():
    os.system('cls' if os.name == 'nt' else 'echo -e \\\\033c')

clear() # Clear the screen before beginning

print ("Let's perform some calculations! \n")
print ("Please input your numbers! \n")
print ("When finished, press any non-numeric key to complete the calculations! \n")

try: # Loop will end when an input other than a number is submitted
    numbers = []

    while True:
        print ("Enter number:")
        numbers.append(float(input())) # Use float() instead of int() for decimals
        clear()

except:
        clear()
        print ("\nThe average of the values is ", (("{:,.2f}".format(mean(numbers)))))
        print ("\nThe summation of the input is ", (("{:,.2f}".format(sum(numbers)))))
        print ("\nThe maximum value of the input is ", (("{:,.2f}".format(max(numbers)))))
        print ("\nThe minimum value of the input is ", (("{:,.2f}".format(min(numbers)))))
        print ("\nThe range of the values is", (("{:,.2f}".format(max(numbers) - min(numbers)))))
        print ("\n\n")
