#!/usr/bin/python3
import os
from statistics import mean

#Define the Clear Function
def clear():
    os.system('cls' if os.name == 'nt' else 'echo -e \\\\033c')

clear() # Clear the screen before beginning

print ("Let's perform some calculations! \n")
print ("Please input your numbers! \n")
print ("When finished, press any non-numeric key to complete the calculations! \n")

try: # Loop will end when an input other than a number is submitted
    numbers = []

    while True:
        print ("Enter number:")
        numbers.append(float(input())) # Use float() instead of int() for decimals
        clear()

except:
        clear()
        print ("\nThe average of the numbers is:", mean(numbers))
        print ("\n")
        print ("The maximum value of the input is", max(numbers))
        print ("\n")
        print ("The minimum value of the input is", min(numbers))
        minMax = (max(numbers) - min(numbers))
        print("\n")
        print ("The delta of the values is", (minMax))
        print ("\n\n")
